"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
    'plist': {
        'PyRuntimeLocations': [
                               '@executable_path/../Frameworks/libpython3.5m.dylib',
'/Users/kado/.pyenv/versions/anaconda3-2019.03/envs/py35pyside2/lib/libpython3.5m.dylib'
                               ]
            }}

setup(
    name='imageCutter',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
